# Generated by Django 2.1.7 on 2019-03-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aqua_app', '0004_auto_20190315_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqua_app.Usuario'),
        ),
    ]
