# Generated by Django 2.1.7 on 2019-03-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua_app', '0006_auto_20190315_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
